apiVersion: apps/v1
kind: Deployment
metadata:
  lables:
   app: mariadb
  name: mariadb_Deployment
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: docker.io/mariadb:10.4
        ports:
        - containerPort: 3306
          protocol: TCP